config/routes.rb
Depot::Application.routes.draw do
  resources :line_items

  resources :carts

  get "store/index"

  resources :products
  root :to => 'store#index'
  

end

app/models/cart.rb
class Cart < ActiveRecord::Base
 has_many :line_items, dependent: :destroy
 def add_product(product_id)
	 current_item = line_items.find_by_product_id(product_id)
	 if current_item
		 current_item.quantity += 1
	 else
		 current_item = line_items.build(product_id: product_id)
	 end
	 current_item
 end
end

app/models/line_item.rb
class LineItem < ActiveRecord::Base
	belongs_to :product
	belongs_to :cart
end

app/models/product.rb
#encoding: utf-8
class Product < ActiveRecord::Base
  has_many :line_items
  
  before_destroy :ensure_not_referenced_by_any_line_item
  
  validates :title, :description, :image_url, presence: true
  validates :price,numericality: {greater_than_or_equal_to: 0.01}
  validates :title,uniqueness: true
  validates :image_url, allow_blank: true, format: {
    with: %r{\.(gif|jpg|png)$}i,
    message: 'はGIF、JPG、PNGのURLでなければなりません。'
  }
  validates :title, :length => {
    :minimum => 5
    #, :message => "must be at least ten characters long." 
  }
  
  private
  # この商品を参照している品目が無いことを確認する
  def ensure_not_referenced_by_any_line_item
    if line_items.empty?
      return true
    else
      errors.add(:base,'品目が存在します')
      return false
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
  private 
  def current_cart
    Cart.find(session[:cart_id])
  rescue ActiveRecord::RecordNotFound
    cart = Cart.create
    session[:cart_id] = cart.id
    cart
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  # GET /carts
  # GET /carts.json
  def index
    @carts = Cart.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @carts }
    end
  end

  # GET /carts/1
  # GET /carts/1.json
  def show
    @cart = Cart.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @cart }
    end
  end

  # GET /carts/new
  # GET /carts/new.json
  def new
    @cart = Cart.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @cart }
    end
  end

  # GET /carts/1/edit
  def edit
    @cart = Cart.find(params[:id])
  end

  # POST /carts
  # POST /carts.json
  def create
    @cart = Cart.new(params[:cart])

    respond_to do |format|
      if @cart.save
        format.html { redirect_to @cart, notice: 'Cart was successfully created.' }
        format.json { render json: @cart, status: :created, location: @cart }
      else
        format.html { render action: "new" }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /carts/1
  # PUT /carts/1.json
  def update
    @cart = Cart.find(params[:id])

    respond_to do |format|
      if @cart.update_attributes(params[:cart])
        format.html { redirect_to @cart, notice: 'Cart was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carts/1
  # DELETE /carts/1.json
  def destroy
    @cart = Cart.find(params[:id])
    @cart.destroy

    respond_to do |format|
      format.html { redirect_to carts_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/line_items_controller.rb
class LineItemsController < ApplicationController
  # GET /line_items
  # GET /line_items.json
  def index
    @line_items = LineItem.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @line_items }
    end
  end

  # GET /line_items/1
  # GET /line_items/1.json
  def show
    @line_item = LineItem.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @line_item }
    end
  end

  # GET /line_items/new
  # GET /line_items/new.json
  def new
    @line_item = LineItem.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @line_item }
    end
  end

  # GET /line_items/1/edit
  def edit
    @line_item = LineItem.find(params[:id])
  end

  # POST /line_items
  # POST /line_items.json
  def create
    @cart = current_cart
		product = Product.find(params[:product_id])
		@line_item = @cart.add_product(product.id)
		
    respond_to do |format|
      if @line_item.save
			session[:counter] = 0
        format.html { redirect_to @line_item.cart, notice: 'Line item was successfully created.' }
        format.json { render json: @line_item, status: :created, location: @line_item }
      else
        format.html { render action: "new" }
        format.json { render json: @line_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /line_items/1
  # PUT /line_items/1.json
  def update
    @line_item = LineItem.find(params[:id])

    respond_to do |format|
      if @line_item.update_attributes(params[:line_item])
        format.html { redirect_to @line_item, notice: 'Line item was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @line_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /line_items/1
  # DELETE /line_items/1.json
  def destroy
    @line_item = LineItem.find(params[:id])
    @line_item.destroy

    respond_to do |format|
      format.html { redirect_to line_items_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  # GET /products
  # GET /products.json
  def index
    @products = Product.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @products }
    end
  end

  # GET /products/1
  # GET /products/1.json
  def show
    @product = Product.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @product }
    end
  end

  # GET /products/new
  # GET /products/new.json
  def new
    @product = Product.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @product }
    end
  end

  # GET /products/1/edit
  def edit
    @product = Product.find(params[:id])
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(params[:product])

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render json: @product, status: :created, location: @product }
      else
        format.html { render action: "new" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /products/1
  # PUT /products/1.json
  def update
    @product = Product.find(params[:id])

    respond_to do |format|
      if @product.update_attributes(params[:product])
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product = Product.find(params[:id])
    @product.destroy

    respond_to do |format|
      format.html { redirect_to products_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/store_controller.rb
class StoreController < ApplicationController
  def index
    @products = Product.order(:title)
    @current_time = Time.now.strftime("%H:%M:%S")
  end
	
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/store_helper.rb
module StoreHelper
	def reset_index_visits
		session[:counter]=0
	end
	
	def count_index_visits
		if session[:counter].nil?
			reset_index_visits
		else
			session[:counter] +=1
		end
		if session[:counter] > 5 then
			session[:counter]
		end
	end
	
	def report_index_visits
		if session[:counter] ==1 then
			response = "Welcome!"
		else
			response = "Black for your"+session[:counter].to_s+"th visit?"
		end
		return response
	end
end

app/views/carts/_form.html.haml
= form_for @cart do |f|
  -if @cart.errors.any?
    #error_explanation
      %h2= "#{pluralize(@cart.errors.count, "error")} prohibited this cart from being saved:"
      %ul
        - @cart.errors.full_messages.each do |msg|
          %li= msg

  .actions
    = f.submit 'Save'

app/views/carts/edit.html.haml
%h1 Editing cart

= render 'form'

= link_to 'Show', @cart
\|
= link_to 'Back', carts_path

app/views/carts/index.html.haml
%h1 Listing carts

%table
  %tr
    %th
    %th
    %th

  - @carts.each do |cart|
    %tr
      %td= link_to 'Show', cart
      %td= link_to 'Edit', edit_cart_path(cart)
      %td= link_to 'Destroy', cart, :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New Cart', new_cart_path

app/views/carts/new.html.haml
%h1 New cart

= render 'form'

= link_to 'Back', carts_path

app/views/carts/show.html.haml
%p#notice= notice

%h2 Pragmaticカート
%ul
	- @cart.line_items.each do |item|
		%li
			= item.quantity
			&times;
			= item.product.title

= link_to 'Edit', edit_cart_path(@cart)
\|
= link_to 'Back', carts_path

app/views/layouts/application.html.haml
!!!
%html{:lang => "en"}
  %head
    %meta{:charset => "utf-8"}
      %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}
        %title Depot
        = csrf_meta_tags
        / Le HTML5 shim, for IE6-8 support of HTML elements
        /[if lt IE 9]
          <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>

        / Le styles
        = stylesheet_link_tag "application", :media => "all"
        / Le fav and touch icons
        %link{:href => "images/favicon.ico", :rel => "shortcut icon"}
          %link{:href => "images/apple-touch-icon.png", :rel => "apple-touch-icon"}
            %link{:href => "images/apple-touch-icon-72x72.png", :rel => "apple-touch-icon", :sizes => "72x72"}
              %link{:href => "images/apple-touch-icon-114x114.png", :rel => "apple-touch-icon", :sizes => "114x114"}
  %body{:class => controller.controller_name}
    .navbar.navbar-fixed-top
      .navbar-inner
        .container
          %a.btn.btn-navbar{"data-target" => ".nav-collapse", "data-toggle" => "collapse"}
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          %a.brand{:href => "#"} Depot
          .container.nav-collapse
            %ul.nav
              %li= link_to "Home", "/"
              %li= link_to "FAQ", "/"
              %li= link_to "News", "/"
              %li= link_to "問い合わせ", "/"
          / /.nav-collapse
    .container
      .content
        .row
          .span9
            = yield
          .span3
            .well.sidebar-nav
              %h3 Sidebar
              %ul.nav.nav-list
                %li.nav-header SidebarLoad:
                %span #{@current_time}
                %li= link_to "Home", "/"
                %li= link_to "FAQ", "/"
                %li= link_to "News", "/"
                %li= link_to "問い合わせ", "/"
            / /.well
          / /span
        / /row
      / /content
      %footer
        %p © Company 2012
    / /container
    /
      Le javascript
      \==================================================
    / Placed at the end of the document so the pages load faster
    = javascript_include_tag "application"

app/views/line_items/_form.html.haml
= form_for @line_item do |f|
  -if @line_item.errors.any?
    #error_explanation
      %h2= "#{pluralize(@line_item.errors.count, "error")} prohibited this line_item from being saved:"
      %ul
        - @line_item.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :product_id
    = f.number_field :product_id
  .field
    = f.label :cart_id
    = f.number_field :cart_id
  .actions
    = f.submit 'Save'

app/views/line_items/edit.html.haml
%h1 Editing line_item

= render 'form'

= link_to 'Show', @line_item
\|
= link_to 'Back', line_items_path

app/views/line_items/index.html.haml
%h1 Listing line_items

%table
  %tr
    %th Product
    %th Cart
    %th
    %th
    %th

  - @line_items.each do |line_item|
    %tr
      %td= line_item.product_id
      %td= line_item.cart_id
      %td= link_to 'Show', line_item
      %td= link_to 'Edit', edit_line_item_path(line_item)
      %td= link_to 'Destroy', line_item, :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New Line item', new_line_item_path

app/views/line_items/new.html.haml
%h1 New line_item

= render 'form'

= link_to 'Back', line_items_path

app/views/line_items/show.html.haml
%p#notice= notice

%p
  %b Product:
  = @line_item.product_id
%p
  %b Cart:
  = @line_item.cart_id

= link_to 'Edit', edit_line_item_path(@line_item)
\|
= link_to 'Back', line_items_path

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description, rows: 6%>
  </div>
  <div class="field">
    <%= f.label :image_url %><br />
    <%= f.text_field :image_url %>
  </div>
  <div class="field">
    <%= f.label :price %><br />
    <%= f.text_field :price %>
  </div>
  <div class="action"> 
    <%= f.submit :class => "btn btn-primary" %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<h1>Listing products</h1>

<table class="table table-striped">
<% @products.each do |product| %>
	<tr class="<%= cycle('list_line_odd', 'list_line_even') %>">
		<td>
			<%= image_tag(product.image_url, class: 'list_image') %> 
		</td>
		<td class="list_description"> <dl>
			<dt><%= product.title %></dt>
			<dd><%= truncate(strip_tags(product.description),
				length: 80) %></dd>
			</dl> 
		</td>
		<td class="list_actions">
			<%= link_to 'Show', product %><br/>
			<%= link_to 'Edit', edit_product_path(product) %><br/> 
			<%= link_to 'Destroy', 	product,
						confirm: 'Are you sure?', 
						method: :delete %>
		</td> 
	</tr>
<% end %>
</table>
<br />
<%= link_to new_product_path,:class => 'btn btn-primary btn-small' do %>
	<i class="icon-plus"></i>
	<span>New product</span>
<% end %>

app/views/products/new.html.erb
<h1>New product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @product.title %>
</p>

<p>
  <b>Description:</b>
  <%= @product.description %>
</p>

<p>
  <b>Image url:</b>
  <%= @product.image_url %>
</p>

<p>
  <b>Price:</b>
  <span class="price"><%= @product.price %></span>
</p>


<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>

app/views/store/index.html.haml
- if notice
	%p#notice= notice

= count_index_visits 
%h1 Pragmaticカタログ
%p= report_index_visits
- @products.each do |product|
	.entry
		// = image_tag(product.image_url)
		= link_to image_tag(product.image_url),
			line_items_path(:product_id => product),
			:method => :post
		%h3= product.title
		= sanitize(product.description)
		.price_line
			//%span.price= product.price
			%span.price= number_to_currency(product.price)
			.btn-group
			= button_to 'カートに入れる',line_items_path(product_id: product) ,:class => 'btn btn-primary btn-small'